name: Test & Deploy

on:
  
  push:
    branches: [ master ]

jobs:
  
  build:
    
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
          
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity normal test
        
      - name: Install Fable tool
        run: dotnet tool restore
    
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.3.0
        with:
          node-version: v16.4.x
    
      - run: npm install
      - run: npm run build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: deploy # The folder the action should deploy.
